# Generated by Django 5.0.6 on 2024-07-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("release_date", models.DateField()),
                ("required_age", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("dlc_count", models.IntegerField()),
                ("about", models.TextField()),
                ("supported_languages", models.TextField()),
                ("windows", models.BooleanField()),
                ("mac", models.BooleanField()),
                ("linux", models.BooleanField()),
                ("positive", models.IntegerField()),
                ("negative", models.IntegerField()),
                ("score_rank", models.CharField(blank=True, max_length=50, null=True)),
                ("developer", models.CharField(max_length=255)),
                ("publishers", models.TextField()),
                ("categories", models.TextField()),
                ("genres", models.TextField()),
                ("tags", models.TextField()),
            ],
        ),
    ]
