# Generated by Django 5.0.6 on 2024-07-07 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="developer",
            new_name="developers",
        ),
    ]
